#!/bin/sh

set -x

[ ! -z $1 ] \
        && pkgs=$@ \
        || pkgs=$(cat ~/.cache/pkglist | awk '{print $2}' | dmenu -l 20 )
echo $pkgs

for pkg in $pkgs
do
    yay -S --noconfirm --sudo $HOME/.scripts/plz $pkg
done
