#!/bin/python

import os
import subprocess

os.system("dunstctl close-all")
os.system("dunstctl set-paused true")
os.system("xscreensaver-command -lock")
lock_watch = subprocess.Popen(["xscreensaver-command", "-watch"], stdout=subprocess.PIPE)
while True:
    line = lock_watch.stdout.readline().decode("UTF-8")
    if line.split(" ")[0] == 'UNBLANK':
        break

os.system("dunstctl set-paused false")
